# tasks file for docker-registry
- name: login dockerhub
  vars:
   ansible_python_interpreter: /usr/bin/python3
  docker_login:
    username: "samarbelhadj"
    password: "Samar123**"
- name: push to dockerhub
  docker_image:
    name: devops:latest
    repository: samarbelhadj/devops
    push: yes
    source: local
