---
# tasks file for docker-registry
- name: login dockerhub
  docker_login:
    username: "riadhmars"
    password: "marsmars2022"
- name: push to dockerhub
  docker_image:
    name: appfront:latest
    repository: riadhmars/frontprojet
    push: yes
    source: local
