---
# tasks file for docker
        - name: create docker image
          docker_image:
            name: devops
            build:
             path: /var/lib/jenkins/workspace/CI-CD-Angular
             pull: no
            source: build
            state: present
            force_source: true
        - name: run docker container
          docker_container:
            name: myapp_container
            image: devops:latest
            state: started
            recreate: true
            ports:
             - "4200:80"
